include:
  - component: $CI_SERVER_FQDN/library/to-be-continuous/Docker/gitlab-ci-docker@master
    inputs:
      # Тесты
      build-tool: buildah
      build-args: "--format=docker"
      config-file: "/tmp/config.json"
      
      prod-publish-strategy: auto
      
      release-extra-tags: latest \g<major>.\g<minor> \g<major>
      semrel-release-disabled: true
      
      cosign-strategy: always
      cosign-dist-url: "https://github.com/sigstore/cosign/releases/download/v2.5.0/cosign-linux-amd64"

  - component: $CI_SERVER_FQDN/library/cicd/extands/docker-image-mirroring/docker-image-mirroring@main

  - component: $CI_SERVER_FQDN/library/cicd/auto-release/auto-release@main
    inputs:
      auto-rebase: true
      auto-approve: true

      auto-merge: true
      auto-remove-source-branch: true

      auto-tag: false
      auto-tag-pattern: '/^\d+\.\d+\.\d+$/'
      auto-tag-version-major: 0
      auto-tag-version-minor: 4

      auto-release: true

stages:
  - build                                # docker-hadolint,
  - package-build                        # docker-kaniko-build, docker-dind-build, docker-buildah-build
  - package-test                         # docker-healthcheck, docker-trivy, docker-sbom
  - publish                              # docker-publish

  - auto-merge
  - auto-tag
  - auto-release

.docker-base:
  services:
    - name: "$TBC_TRACKING_IMAGE"
      command: ["--service", "docker", "8.0.10"]
  before_script:
    - !reference [.docker-scripts]
  tags:
    - docker-builder

.docker-buildah-mirroring-needs:
  - job: docker-publish

.auto-rebase-needs:
  - job: docker-hadolint
    optional: true
  - job: docker-buildah-build
    optional: true
  - job: docker-healthcheck
    optional: true
  - job: docker-sbom
    optional: true
  - job: docker-trivy
    optional: true
  - job: docker-publish

.auto-approve-needs:
  - job: docker-hadolint
    optional: true
  - job: docker-buildah-build
    optional: true
  - job: docker-healthcheck
    optional: true
  - job: docker-sbom
    optional: true
  - job: docker-trivy
    optional: true
  - job: docker-publish

.auto-merge-needs:
  - job: docker-hadolint
    optional: true
  - job: docker-buildah-build
    optional: true
  - job: docker-healthcheck
    optional: true
  - job: docker-sbom
    optional: true
  - job: docker-trivy
    optional: true
  - job: docker-publish

.auto-create-TAG-needs:
  - job: docker-hadolint
    optional: true
  - job: docker-buildah-build
    optional: true
  - job: docker-healthcheck
    optional: true
  - job: docker-sbom
    optional: true
  - job: docker-trivy
    optional: true
  - job: docker-publish

.auto-release-needs:
  - job: docker-hadolint
    optional: true
  - job: generate_release_env_file
  - job: docker-buildah-build
    optional: true
  - job: docker-healthcheck
    optional: true
  - job: docker-sbom
    optional: true
  - job: docker-trivy
    optional: true
  - job: docker-publish
  - job: docker-buildah-mirroring
    optional: true

generate_release_env_file:
  stage: publish
  image: registry.gitlab.com/gitlab-org/cli:latest
  needs:
    - job: docker-publish
  before_script:
    - !reference [ .install-utility ]
  script:
    - |
      arg_image=$(printf '```bash\ndocker pull %s:%s\n```\n' \
        "$CI_REGISTRY_IMAGE" "$docker_tag")

      log_info "$arg_image"
      
      arg_latest=$(printf '```bash\ndocker pull %s:%s\n```\n---\n' \
        "$CI_REGISTRY_IMAGE" "latest")
      
      log_info "$arg_latest"
      
      # Формируем release notes для образа docker
      release_notes_docker=$(jq -n \
        --arg head "Docker image" \
        --arg image "$arg_image" \
        --arg latest "$arg_latest" \
        '{head: $head, image: $image, latest: $latest}' | base64 -w0
      )

      {
        echo "release_notes_docker=$release_notes_docker"
      } > release.env

  rules:
    - !reference [ .tagged, only ]
    - when: on_success
  artifacts:
    reports:
      dotenv: release.env

variables:
  CI_DEBUG_TRACE: "false"
  TRACE: "false"
  CUSTOM_CA_CERTS: "$CI_SERVER_TLS_CA_FILE"
  DEFAULT_CA_CERTS: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  
  COSIGN_TLS_PATH: "/etc/ssl/cosign/"
  COSIGN_PRIVATE_KEY: "gitlab://${CI_PROJECT_ID}"
  COSIGN_PASSWORD: "$CI_COMMIT_REF_SLUG"

  DOCKER_MIRROR_REPO: "ghcr.io/fzen475/gitlab-ci-validate" #repository name must be lowercase
